	<title>Privacy Policy - Dil ki Awaz</title>
 <style>
        .blue-subhead{color: rgb(0, 0, 59);}
        .lightblue-subhead{color: rgb(0, 160, 213);}
    </style>
<div class="row">
  <div class="tab-content">
    <div class="container">      
<div>
        <h1>Privacy Policy</h1>
        <p>Last updated: August 21, 2022</p>
        <p>This Privacy Policy describes Our policies and procedures on the collection,
            use and disclosure of Your information when You use the Service and tells
            You about Your privacy rights and how the law protects You.</p>
        <p>We use Your Personal data to provide and improve the Service. By using the Service,
            You agree to the collection and use of information in accordance with this Privacy Policy.
            This Privacy Policy has been created with the help of the Free Privacy Policy Generator.</p><br>
    </div>
    <div>
        <h1 class="blue-subhead">Interpretation and Definitions </h1>
        <hr>
        <div>
            <h3 class="lightblue-subhead">Interpretation</h3>
            <p>
                The words of which the initial letter is capitalized have meanings defined under the following conditions.
                The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
            </p>
        </div>
        <div>
            <h3 class="lightblue-subhead">Definitions</h3>
            <p>For the purposes of this Privacy Policy:</p>
            <div>
                <p><b>Account</b> means a unique account created for You to access our Service or parts of our Service.</p>
                <p><b>Affiliate</b> means an entity that controls, is controlled by or is under common control with a party,
                 where "control" means ownership of 50% or more of the shares,
                 equity interest or other securities entitled to vote for election of directors or other managing authority.</p>
                <p><b>Application or App</b> means the software program provided by the Company downloaded by You on any electronic device,
                 named Dil ki Awaz: Urdu Audiobooks</p>
                <p><b>Company</b> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to <u>Dil ki Awaz: Urdu Audiobooks.</u></p>
                <p><b>Country </b> refers to: United Kingdom</p>
                <p><b>Device </b> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</p>
                <p><b>Personal Data </b> is any information that relates to an identified or identifiable individual.</p>
                <p><b>Service </b> refers to the Application.</p>
                <p><b>Service Provider  </b> means any natural or legal person who processes the data on behalf of the Company.
                 It refers to third-party companies or individuals employed by the Company to facilitate the Service,
                 to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</p>
                <p><b>Usage Data  </b> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself
                 (for example, the duration of a page visit).</p>
                <p><b>You  </b> means the individual accessing or using the Service, or the company,
                  or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p><br>

            </div>

        </div>

    </div>
    <div>
        <h1 class="blue-subhead">Collecting and Using Your Personal Data </h1><hr>
        <div>
          <h3 class="lightblue-subhead">Types of Data Collected</h3>
          <h4 class="lightblue-subhead">Personal Data</h4>
          <p>
            While using Our Service, We <b>DO NOT</b> ask You to provide Us with any
            personally identifiable information that can be used to contact or identify You.
           </p>
           <h4 class="lightblue-subhead">Usage Data</h4>
           <p>
            The App <b>does not</b> collect Usage Data when using the Service.
           </p>
           <h3 class="lightblue-subhead">Use of Your Personal Data</h3>
           <p>The Company <b>does not</b> collect <b>nor use</b> Personal Data for any purpose including to provide and maintain our Service,
            to manage Your Account, for the performance of a contract, to contact You or for other purposes such as data analysis,
            identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service,
            products, services, marketing and your experience. <br> <br>
            We <b>will not</b> will not collect <b>nor share</b> Your personal information with anyone including with Service Providers,
            for business transfers, with Affiliates, with business partners or with other users.</p>
           <h3 class="lightblue-subhead">Retention of Your Personal Data</h3>
           <p>The Company will not collect nor retain Your Personal Data </p>

           <h3 class="lightblue-subhead">Transfer of Your Personal Data</h3>
           <p>We do not collect nor transfer your Personal Data anywhere or to anyone. </p>

           <h3 class="lightblue-subhead">Disclosure of Your Personal Data</h3>
           <p>We do not collect hence will not be able to disclose your Personal Data. </p>
        </div>
    </div>
    <div>
        <h1 class="blue-subhead">Children's Privacy</h1><hr>
        <p>We do not collect personally identifiable information from anyone under the age of 13.
            If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.
            If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent,
            We take steps to remove that information from Our servers. If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent,
            We may require Your parent's consent before We collect and use that information.</p>
        <div>
            <p><b>App content:</b> Audiobooks uploaded on the app shall be appropriate for children and adults of all ages globally.</p>
            <p><b>App functionality: </b>The App is not merely a webview of a website. It is a well-designed app to make it user friendly for users of all ages including children.</p>
            <p><b>Ads:</b> Our app does not have any ads</p>
            <p><b>Data practices:</b>The App does not collect any personal and sensitive information from any user including children
                  including through APIs and SDKs called or used in the App. The App does not transmit AAID, SIM serial, build serial, BSSID,
                  MAC, SSID, IMEI and/or IMSI from children or any other users. The App does not request device phone number.</p>
            <p><b>Augmented reality: </b>The App does not use augmented reality features</p>
            <p><b>Social apps and features:</b>The App does not allow users to share or exchange information.</p>
        </div>
    </div>
    <div>
        <h1 class="blue-subhead">Links to Other Websites</h1><hr>
        <p>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link,
           You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.<br>
           We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
            </p>
    </div>
    <div>
        <h1 class="blue-subhead">Changes to this Privacy Policy</h1><hr>
        <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.<br>
            We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.<br>
            You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
        </p>
    </div>
    <div>
        <h1 class="blue-subhead">Contact Us</h1><hr>
        <p>If you have any questions about this Privacy Policy, You can contact us:</p>
        <ul>
            <li>By email: urduabproject@gmail.com</li>
        </ul>
    </div>
</div>
